# Reference: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/storing-and-sharing-data-from-a-workflow
name: Artifacts
run-name: Proving Artifacts
on: [push]
jobs:
  Share-Data-With-Another-Job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "100" > my-artifact.txt
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: my-artifact.txt
          retention-days: 5
  Receiving-Data-From-Another-Job:
    runs-on: ubuntu-latest
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
      - run: cat my-artifact.txt
