name: Secret Scanning - Gitleaks

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  scan:
    name: Scan for secrets - Gitleaks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Gitleaks
        run: |
          curl -sSfL https://github.com/zricethezav/gitleaks/releases/download/v8.0.0/gitleaks_8.0.0_linux_x64.tar.gz | tar xz
          sudo mv gitleaks /usr/local/bin/gitleaks

      - name: Run Gitleaks
        run: gitleaks detect --config=.gitleaks.toml --verbose
